@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Nov 18 08:50:53 -0800 2020
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim dot_product_tb_behav -key {Behavioral:sim_1:Functional:dot_product_tb} -tclbatch dot_product_tb.tcl -view C:/Users/phatle/Stripe_DotProduct/dot_product_tb_behav.wcfg -log simulate.log"
call xsim  dot_product_tb_behav -key {Behavioral:sim_1:Functional:dot_product_tb} -tclbatch dot_product_tb.tcl -view C:/Users/phatle/Stripe_DotProduct/dot_product_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
