webtalk_init -webtalk_dir C:/Users/phatle/dot_product/dot_product.sim/sim_1/behav/xsim/xsim.dir/dot_product_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug  4 17:51:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4e203288-ee35-4c31-a431-53b57b0f1b44" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d088d7aa3ef14cd89978181a84d98d8b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "88" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "12" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "89 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "62" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "23" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.76_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "45252_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2120342134 -regid "" -xml C:/Users/phatle/dot_product/dot_product.sim/sim_1/behav/xsim/xsim.dir/dot_product_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/phatle/dot_product/dot_product.sim/sim_1/behav/xsim/xsim.dir/dot_product_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/phatle/dot_product/dot_product.sim/sim_1/behav/xsim/xsim.dir/dot_product_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
